### ISSUE TITLE
Need to press the tab twice

### ISSUE THREAD

**Issue by ChillarAnand** [ervandew/supertab#107]
Lets say i have typed this

$variable = '1';
$va

now to autocomplete the remaining i need to press the tab twice once to cycle and once to insert. Instead of that, is it possible to insert the auto complete text with single tab?

Please help with this! Thank you

**Comment by kiryph** [comment]
I stumbled upon this with the same issue. A little bit of googling has brought some noteworthy information:

There is actually a discussion at the repository of autocomplpop about this issue
https://bitbucket.org/ns9tks/vim-autocomplpop/issue/53/make-autoselection-of-the-first-item 

However the author of autocomplpop (ns9tks) is not active anymore.

There is fork which implements the desired behaviour:
https://github.com/dirkwallenstein/vim-autocomplpop

The author of this fork has also written a blog post about a powerful completion mode which combines different sources: http://vertuxeltes.blogspot.de/2013/05/powerful-insert-mode-completion.html
