### ISSUE TITLE
Any way to make g:SuperTabCrMapping = 0 not add a return

### ISSUE THREAD

**Issue by benfrain** [ervandew/supertab#127]
Just starting to use supertab and think I must have missed something in the docs.

I like pressing `<C-r>` to complete. Therefore I have set `let g:SuperTabCrMapping = 0` in my vimrc.

However, having done this I get both completion on return (`<C-r>`) but also a return in insert mode (e.g. puts me onto the next line).

How do I get a `<C-r>` with Supertab invoked just do a complete (and not add the return)?

**Comment by robbyki** [comment]
Having same issue. Sorry, but I didn't understand what the solution was here. How do I make it so that I don't get a new line when I press enter on a suggestion?
