### ISSUE TITLE
Pressing enter results in a new line

### ISSUE THREAD

**Issue by jerzygangi** [ervandew/supertab#142]
Hi,

When I type the beginning of a word, and then press `<Tab>` to active supertab, and then press `<Enter>` to select the first item, I get the selected item but also a newline.

I would expect `<Enter>` to select the item in supertab, but not to create a newline. (As a result, I'm always having to type `<Backspace>` after pressing `<Enter>` to go back onto the line I was typing on.)

Is there a way to make `<Enter>` simply select the highlighted item in supertab instead of also creating a newline?

**Comment by gummesson** [comment]
You could use [`<C-y>`](http://vimdoc.sourceforge.net/htmldoc/insert.html#complete_CTRL-Y). For more information, see [ins-completion](http://vimdoc.sourceforge.net/htmldoc/insert.html#ins-completion). :)

**Comment by jerzygangi** [comment]
It appears github did not format my issue correctly. I've just edited it to fix the problem.

**Comment by jerzygangi** [comment]
@gummesson I want to press `<Enter>`, not `<C-y>`. `<Enter>` is instinctual and just makes sense.

**Comment by ervandew** [comment]
If you add the following to your vimrc then supertab will map `<cr>` to choose the currently highlighted text and end completion mode, without inserting a new line:

    let g:SuperTabCrMapping = 1

Until recently this was the default, but there are other plugins which also want to map to `<cr>`, so sometimes this mapping can conflict with those. Supertab tries to retain compatibility with other plugins, but this doesn't work for all users/plugin combinations, so this feature is now disabled by default.

**Comment by jerzygangi** [comment]
That works, @ervandew. Thnx.

**Comment by aaronamm** [comment]
@ervandew  Tab and enter is more natural. Thank you for the solution.
Thanks @jerzygangi for opening such a useful issue.
