### ISSUE TITLE
eclim + context completion type appears broken for PHP

### ISSUE THREAD

**Issue by briceburg** [ervandew/supertab#144]
```php
class SiteTree extends DataObject {
    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        $fields->|
        ...
    }
```

Invoking SuperTab at the cursor position indicated by | brings up tag omnicompletion `<Ctrl-X><Ctrl-O>`,  where I believe it is supposed to invoke the user completefunc `<Ctrl-X><Ctrl-U>` provided by Eclim. 

The tags are limited, and the completefunc provides my desired autocompletions (methods of SiteTree).

My .vimrc includes
```
let g:SuperTabDefaultCompletionType = 'context'
```

Any pointers appreciated!

**Comment by briceburg** [comment]
As a quick followup after diffing through the docs;

I was able to bring up the completefunc by setting the ContextDefaultCompletion type to the user completefunc via:

```vim
let g:SuperTabDefaultCompletionType = 'context'
let g:SuperTabContextDefaultCompletionType = '<c-x><c-u>'
```

I setup code completion following the eclim docs;
  http://eclim.org/vim/code_completion.html

Do you want me to add the `g:SuperTabContextDefaultCompletionType` setting to those docs and send a PR? or am I still doing/expecting something wrong?

Thanks as ever for your work.

**Comment by ervandew** [comment]
> Invoking SuperTab at the cursor position indicated by | brings up tag omnicompletion `<Ctrl-X><Ctrl-O>`, where I believe it is supposed to invoke the user completefunc `<Ctrl-X><Ctrl-U>` provided by Eclim.

It should default to user completion if `&completefunc` is set, unless you've defined `g:SuperTabContextTextOmniPrecedence` to put `&omnifunc` first.

> I was able to bring up the completefunc by setting the ContextDefaultCompletion type to the user completefunc via:
>
>     let g:SuperTabDefaultCompletionType = 'context'
>     let g:SuperTabContextDefaultCompletionType = '<c-x><c-u>'
> 
> I setup code completion following the eclim docs;
> http://eclim.org/vim/code_completion.html
> 
> Do you want me to add the `g:SuperTabContextDefaultCompletionType` setting to those docs and send a PR?

No, that setting is not necessary, and as you've seen, it affects all file types regardless of whether they have user completion support or not, so adding that to the docs would confuse users.

> or am I still doing/expecting something wrong?

Can you open your php file and check the following:

    :verbose set completefunc?
    :echo g:SuperTabContextTextOmniPrecedence
    " check the buffer local version
    :echo b:SuperTabContextTextOmniPrecedence

**Comment by briceburg** [comment]
Interesting, it doesn't seem g:SuperTabContextTextOmniPrecedence  is set -- although b: is

```vim
:verbose set completefunc?
    completefunc=eclim#php#complete#CodeComplete
    Last set from /usr/share/vim/vimfiles/eclim/ftplugin/php.vim

:echo g:SuperTabContextTextOmniPrecedence
    E121: Undefined variable: g:SuperTabContextTextOmniPrecedence
    E15: Invalid expression: g:SuperTabContextTextOmniPrecedence

:echo b:SuperTabContextTextOmniPrecedence
    ['&omnifunc', '&completefunc']
```

My [.vimrc](https://gist.github.com/briceburg/bf966524dd7af488f589)

**Comment by ervandew** [comment]
Hmm, not sure that vim has a way to see where a variable is last set, so you may have to grep through your .vim dir to see of any of those plugins set that variable. Most likely it will be in an `ftplugin/php*.vim` file, or in an autocmd.

**Comment by ervandew** [comment]
Actually I can reproduce this with a php file, so I'll dig around and see what I come up with.

**Comment by ervandew** [comment]
Ah, it's supertab's html.vim ftplugin that is causing this. Not sure why I have that in there. Let me think on this a bit to see if I can remember.

**Comment by briceburg** [comment]
Cool -- thanks for helping with this. Please take your time. I'm working in Eclipse for now ;)

Happy to help if you point me in the right direction.

**Comment by ervandew** [comment]
Kind of gross, but I added some code to avoid this issue.
