### ISSUE TITLE
Head scratching

### ISSUE THREAD

**Issue by jrean** [ervandew/supertab#147]
Hi,

I would like to understand some points because even after reading the documentation again and again I feel still lost.
I'm making some tests so my vim configuration is pretty clean and not overloaded of plugins and settings.

Here is a list of currently activated plugins:
```
Plugin 'jnurmine/Zenburn'
Plugin 'ervandew/supertab'
Plugin 'shawncplus/phpcomplete.vim'
Plugin '2072/PHP-Indenting-for-VIm'
Plugin 'StanAngeloff/php.vim'
Plugin 'majutsushi/tagbar'
```

Here are the Supertab settings in my vimrc (pretty simple):
```
" Supertab -------------------------------------------------------------------v

set completeopt=longest,menuone

let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabCrMapping = 1

" /Supertab ------------------------------------------------------------------^
```

First, let's edit a `test.txt` file and add the following content:
```
Hello
hello
```

If I start typing the following and hit "Tab" the completion menu popup (^ is the cursor).
```
Hello
hello

1) he^
2) /^
```
1) The menu gives "Hello ; hello" as choices. Great.
2) The menu gives "/Application/ ; /bin/ ; ..." Great.

`let g:SuperTabDefaultCompletionType = "context"` is working good :)

Now, let's edit a .php file:
```
<?php

phpi^
```

Hitting "Tab" results of the following message:
`Pattern not found`

However if I hit `<c-x> <c-o>` the omnicompletion menu popups with the correct `filetype` loaded and give me a list of functions I expect.
As long as I stay in insert mode hitting "Tab" on other words will have the correct behaviour.

As soon as I quit insert mode and fall back to normal mode then go back to insert mode, I lost the `<c-x> <c-o>` completion again with "Tab". I need to `<c-x> <c-o>` to get it working.

- 1) What did I miss about "Context" completion? Why is it not working as expected?
- 2) Other problem I have is when for instance (still in the php file) I type the `dat^` (for date) and hit `<c-x> <c-o>` (because "Tab" won't work) it popups the completion menu, list all available occurrences, BUT erase what I have typed! So I need to type again, then it refresh the menu and I can cycle trough occurrences. Very weird. What did I miss?

--

For my 1) question (and problem) I added the following to my .vimrc:
`let g:SuperTabContextDefaultCompletionType = '<c-x> <c-o>'` and now "Tab" is back and working. But I'm still not confident with my understanding.

- 3) If I understand correctly `<c-x> <c-o>` is for omnifunc, `<c-x> <c-u>` is user specific (tags files for instance) and `<c-x> <c-n> / <c-x> <c-l>` are for words and lines (in buffer completion)? Right?
So if I add `let g:SuperTabContextDefaultCompletionType = '<c-x> <c-o>'`, will it work when I will edit classes and need to rely on my tags file?

As you see I need some (good) light...

Please help.

Thank you for your hard work.

**Comment by ervandew** [comment]
> 1) What did I miss about "Context" completion? Why is it not working as expected?

The `context` completion setting only triggers omni/user completion if supertab thinks you are attempting to complete a member (method, variable, etc). From the supertab docs:

    Currently supertab can recognize method calls or attribute references via '.', '::' or '->'

    ...

    myvar.t<tab>    # will use user completion if completefunc set,
                    # or omni completion if omnifunc set.
    myvar-><tab>    # same as above

So when you attempted to complete `phpi`, supertab didn't see it as a member method call or attribute (no `.`, `::`, or `->` preceding the value you were attempting to complete).

> 2) Other problem I have is when for instance (still in the php file) I type the dat^ (for date) and hit <c-x> <c-o> (because "Tab" won't work) it popups the completion menu, list all available occurrences, BUT erase what I have typed! So I need to type again, then it refresh the menu and I can cycle trough occurrences. Very weird. What did I miss?

My guess is that the php completion is case insensitive, and one or more of the results started with a capital D. Combine that with the `longest` option, and now the longest common value among those completions is indeed the empty string, so that's what vim changed the text to.

> So if I add `let g:SuperTabContextDefaultCompletionType = '<c-x> <c-o>'`, will it work when I will edit classes and need to rely on my tags file?

That tells supertab to pretty much always use omni completion. Whether or not the omni completion relies on your tags files or not depends on the implementation of the plugin you are using to provide that completion.
