### ISSUE TITLE
Any way to change the order of completions?

### ISSUE THREAD

**Issue by eugene-eeo** [ervandew/supertab#149]
I do realise that there are closed issues about changing the order which the first suggestion is selected (i.e. initial scroll position and scroll order) but is there a way to switch the order of suggestions such that the closest one is at the top of the menu rather than at the bottom? E.g.

```
def nam|<tab>
       >name
       name_this
       name_this_longer
```

Where ``|`` is the cursor position and ``>`` is the currently "highlighted" (or selected?) suggestion. I have tried out using ``<c-n>`` and my current settings are somewhat vanilla, as copied from the docs.

```viml
" More super Supertab
let g:SuperTabDefaultCompletionType = "context"
autocmd FileType *
  \ if &omnifunc != '' |
  \   call SuperTabChain(&omnifunc, "<c-p>") |
  \ endif
```

**EDIT**: I realised that you are using plain code blocks for your VimL code snippets, the correct language suffix/directive to use is "viml".

**Comment by ervandew** [comment]
Supertab doesn't have any control over the contents or order of the completion results.  Supertab simply handles feeding the correct keys to vim. The rest is up to vim or the user/omni completion plugins.
