### ISSUE TITLE
SuperTab literally inserting text "context"

### ISSUE THREAD

**Issue by fncll** [ervandew/supertab#150]
If I set:

     let g:SuperTabDefaultCompletionType = "context"

in my .vimrc, the pressing tab with the cursor after any text inserts the text

    context

into the buffer.

    verbose imap <tab>

shows 

    Last set from  ~/.vim/bundle/SuperTab/plugin/supertab.vim

If I don't set the default completion type, SuperTab works as expected.

**Comment by ervandew** [comment]
What version of supertab are you using?
Do you experience this issue when disabling all other plugins?
What is the full result (include the actual mapping) of `verbose imap <tab>`?

**Comment by fncll** [comment]
Version: .41

`:verbose imap <tab>` gives

    i  <Tab>         <C-N>
    Last set from ~/.vim/bundle/SuperTab/plugin/supertab.vim

And yes, it happens if I disable all other plugins...

**Comment by ervandew** [comment]
.41 is a good 5+ years old and pre-dates the support for `context` as completion type.

**Comment by fncll** [comment]
Oof. Sorry about that. I switch to Vundle and it must be picking up a very old version...sorry to waste your time!
