### ISSUE TITLE
Example of using SuperTabContextTextMemberPatterns?

### ISSUE THREAD

**Issue by codeinabox** [ervandew/supertab#151]
Are there any examples of using SuperTabContextTextMemberPatterns? I find the default contexts work quite well with the [PHP omnifunc completion](https://github.com/shawncplus/phpcomplete.vim) but I'd like to use keyword competition for `use` statements eg

```php
use Symfony\Component
```

**Comment by ervandew** [comment]
I don't think that modifying the text member patterns would get you what you want. Instead I think you'd want to add a new context function.

If I'm understanding what you're trying to do, then I think something like this added to an `ftplugin/php.vim` file would do the trick:

    function ContextPhpUse()
      if getline('.') =~ '^use\s\+[a-zA-Z0-9_\\]*\%' . col('.') . 'c'
        return "\<c-x>\<c-k>"
      endif
    endfunction
    let b:SuperTabCompletionContexts = ['ContextPhpUse'] + g:SuperTabCompletionContexts

**Comment by codeinabox** [comment]
@ervandew thank you for the reply, almost works perfectly though first time I tab I get the below error though on second press keyword completion kicks in

> 'dictionary' option is empty

**Comment by ervandew** [comment]
I misread your first message apparently. For some reason I thought you wanted to use dictionary completion, but your message clearly says keyword completion. So just update my example by replacing `"\<c-x>\<c-k>"` with the keyword completion keybinding you want to use: `"\<c-n>"` or `"\<c-x>\<c-n>"`, or the `<c-p>` versions of those.

**Comment by codeinabox** [comment]
Perfect, this is exactly what I was looking for. I had set the default completion to omnifunc but I found with some contexts completefunc was more appropriate and was invoking that manually, now I can try setting up some proper contexts.

**Comment by codeinabox** [comment]
One other question, how do I best avoid this error?

> E122: Function ContextPhpUse already exists, add ! to replace it

**Comment by ervandew** [comment]
Just add the bang `!` after `function`:

    function! ContextPhpUse()
      ...
    endfunction
