### ISSUE TITLE
No chaining happening, completefunc empty

### ISSUE THREAD

**Issue by ddaza** [ervandew/supertab#157]
I've been trying to make this work for some time now.  Omni complete works half the time but it never falls back to the context of the files. I don't know if there is something conflicting or I'm doing stuff wrong. Please help!

if I try to manually do a `<c-x><c-o>`
```
Error detected while processing CompleteDone Auto commands for "<buffer=5>":
E108: No such variable: "b:supertab_completion_mode"
```
if I do a manual `<c-x><c-u>`

```
E764: Option 'completefunc' is not set
```

This is what my vimrc has. 

``` vim
let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabCrMapping = 1
let g:SuperTabLongestEnhanced = 1
let g:SuperTabCompletionContexts = ['s:ContextText', 's:ContextDiscover']
let g:SuperTabContextTextOmniPrecedence = ['&completefunc', '&omnifunc']
let g:SuperTabContextDiscoverDiscovery =  ["&completefunc:<c-x><c-u>", "&omnifunc:<c-x><c-o>"]
autocmd FileType *
      \if &omnifunc != '' |
      \call SuperTabChain(&omnifunc, "<c-p>") |
      \call SuperTabSetDefaultCompletionType("<c-x><c-u>") |
      \endif
```

completefunc
```
 completefunc=
```
omnifunc
```
  omnifunc=tern#Complete
        Last set from ~/.vim/bundle/tern_for_vim/autoload/tern.vim
```

**Comment by ervandew** [comment]
I just pushed a fix for the error you received when manually running `<c-x><c-o>`.

As for the setup of the completion chaining, it looks like tern may be setting `omnifunc` after the `FileType` autocmd has fired, so the call to `SuperTabChain` never occurs. You might have to look into using an 'after' ftplugin to setup your completion chaining in this case:

    $ mkdir -p ~/.vim/after/ftplugin
    $ vim ~/.vim/after/ftplugin/javascript.vim

    if &omnifunc != ''
      call SuperTabChain(&omnifunc, "<c-p>")
    endif

Note: calling `SuperTabSetDefaultCompletionType` won't be necessary if you pull the latest supertab version from github.

**Comment by ddaza** [comment]
That worked! Thank you very much!
