### ISSUE TITLE
Can't achieve desired configuration

### ISSUE THREAD

**Issue by manelgarcia** [ervandew/supertab#159]
Hi there!

First things first, lovely plugin, good job.

I'm just stack trying to accomplish something, that I actually don't know if it's possible. I'll try to explain myself. Right now, that's my situation:
- If I tab after ie: `$app->` I get a list of current methods that can be called for that object
- But if I tab after ie: `str_re` I get a "Pattern not found"
- If I `<ctrl+x and ctrl+o>` then tabbing after `str_re` returns the correct php function list, but then again I don't have my custom classes, to get them back I've to `<ctrl+x ctrl+p>`

That is my configuration:

```
let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabContextDefaultCompletionType = "<c-x><c-o>"
```

My question is: How can I have all possibilities always on tab, so I don't have to change between contexts?

Thanks in advance!

**Comment by ervandew** [comment]
It sounds like perhaps you have both user an omni completion set, but you'd prefer for the supertab context completion to use the omni completion. To verify this can you run the following from your (php or perl) file:

    :verbose set completefunc?
    :verbose set omnifunc?

Assuming this is the case, you probably need to remove the setting of `g:SuperTabContextDefaultCompletionType` from your config and instead add:

    let g:SuperTabContextTextOmniPrecedence = ['&omnifunc', '&completefunc']

You also have the option to use supertabs completion chaining allowing it to try omni complete and fallback to keyword completion if no results are found.

**Comment by manelgarcia** [comment]
>`verbose set completefunc?` returns

`completefunc=`

>`:verbose set omnifunc?` returns

```
omnifunc=phpcomplete#CompletePHP`
 Last set from /Applications/MacPorts/MacVim.app/Contents/Resources/vim/runtime/ftplugin/php.vim
``` 

I also tried removing that line and adding your suggestion but I had no luck.

Also, the suggestions that I supose that come from phpcomplete-extended (ctrl+x ctrl+p) look weird and are incompleted.

I'll tryo to reset everything up and see if I can fix.

Thanks for your time!

**Comment by markkimsal** [comment]
I have the same issue.  Using C-X C-O and C-X C-P in insert mode does what I want, but supertab will only give me results from either omni or completion, not both.

```
:verbose set completefunc?
  completefunc=SuperTabCodeComplete
        Last set from ~/.vim/plugged/supertab/plugin/supertab.vim
:verbose set omnifunc?
  omnifunc=phpcomplete#CompletePHP
        Last set from /usr/share/vim/vim74/ftplugin/php.vim

```
config is
```
let g:SuperTabDefaultCompletionType = "context"

let g:SuperTabContextTextOmniPrecedence = ['&omnifunc', '&completefunc']
  autocmd FileType *
    \ if &omnifunc != '' |
    \   call SuperTabChain(&omnifunc, "<c-p>", 1) |
    \ endif

autocmd FileType php set omnifunc=phpcomplete#CompletePHP
```

**Comment by ervandew** [comment]
@markkimsal 
If you are expecting supertab to build a list containing both the omni and keyword completions, it can't do that. It can only try omni and if and only if there are no results, then fallback to keyword completion.
