### ISSUE TITLE
Combine all possible completions?

### ISSUE THREAD

**Issue by Ps-Pencil** [ervandew/supertab#160]
Currently, I am using context and chaining as described in the doc. Everything works fine, except that after dot '.', I dun get the desired completion. 

Eg. suppose I am in some java files and I have System.out.println somewhere in the file. Now I write System.out.pr and press tab. println is not in the choices. I believe that is because the chaining only happens when the first method returns no result but when it returns something I don't want, the second method (c-p) is not invoked. 

Is there a way to combine all the method and have all choices from all ways of completion displayed?

**Comment by ervandew** [comment]
Unfortunately there is no programmatic way to get the results for any completion types other than omni and user, so to combine the results from any of the other methods would require re-implementing those in vim script.
