### ISSUE TITLE
g:SuperTabLongestHighlight interrupt cursor pos if no match

### ISSUE THREAD

**Issue by ZSaberLv0** [ervandew/supertab#162]
to reproduce:
1. let g:SuperTabLongestHighlight=1
2. start complete in middle of a buffer, which would have no match
3. no match and no complete popup as expected, but cursor would moved to next line unexpectly

note:

remove `|| exists('b:supertab_completion_mode')` from

```
function! s:CompletionMode() " {{{
  return pumvisible() || exists('b:supertab_completion_mode')
endfunction " }}}
```

seems to be able to solve the issue, but not sure whether it would breaks other functions

**Comment by kjyv** [comment]
No update on this? It is pretty unbearable to have the cursor jumping but also not so nice to switch the option off. The above solution seems to work fine for me as well.
The relevant commit is  70f4e9ce which is a different use case to OP and me though.

**Comment by Porges** [comment]
I just encountered this too, trying out `g:SuperTabLongestHighlight` for the first time. Thanks for posting here so I could figure out what the problem was :+1:

**Comment by dmitriyK1** [comment]
+1

Cursor jumps when there is only one completion as well and popup not shown

**Comment by ervandew** [comment]
Applogies for the very long delay on this. The latest commit should resolve the problem.

**Comment by Porges** [comment]
Confirmed. Thanks!
