### ISSUE TITLE
Enable DelimitMate support in SuperTab

### ISSUE THREAD

**Issue by cmcginty** [ervandew/supertab#166]
In my testing I found that DelmitMate's default <S-Tab> keymap is replaced by SuperTab's "SuperTabBackward".

Is there a way that SuperTab could test that if the current/next character is a closing pair (e.g. ",',],},) ) then it would defer to the DelemitMate function instead?

**Comment by ervandew** [comment]
I would prefer to avoid adding more work arounds for more plugins. You can change the supertab keybinding to something else via `g:SuperTabMappingBackward`.
