### ISSUE TITLE
S-TAB  mapping issue

### ISSUE THREAD

**Issue by huaihuaiVV** [ervandew/supertab#177]
i have S-TAB  mapping for other plugin in insert mode,
could super tab  only enable its S-TAB mapping when pumvisible() == true ?

Thanks

**Comment by ervandew** [comment]
Mappings don't work that way. At best you could create a mapping of your own which checks pumvisible() and either delegates to supertab or your other plugin. Alternatively, you could remap supertab to not clash with your other plugin.
