### ISSUE TITLE
"Pattern not found" with garbas/vim-snipmate

### ISSUE THREAD

**Issue by NerdPad** [ervandew/supertab#179]
Hi,

I currently have supertab, and garbas/vim-snipmate installed, and as per the FAQs it should have any conflicts.

The problem occurs when I hit <tab> after a word that has no completion as per supertab, or no snippets as per snipmate.

```
aaaa|<tab>
```

The above gives me ```Pattern not found``` and no literal tab is inserted, and the cursor stays where it was.

If there is no way to fix this, is there a way to change supertab mapping from <Tab> to <Ctrl+Space> so I can avoid this conflict?

**Comment by ervandew** [comment]
This is by design since there is no way in this case for the plugin to know that you want a litteral tab instead of a completion attempt. If you are using gvim, supertab provides a ctrl+tab mapping to insert a litteral tab in this case.

**Comment by NerdPad** [comment]
@ervandew Is the default behavior to attempt the completion, and if nothing is found it will insert the characters listed in the *NoCompletionAfter property.

If I disable vim-snippets, it works as expected. If no completion is found for the word it just inserts literal Tabs. It just doesn't work with vim-snippets enabled as mentioned in the FAQ section.

**Comment by ervandew** [comment]
SuperTabNoCompletionAfter is a list of characters where you don't want to trigger completion when hitting `<tab>` when one of those characters is present immediately before the cursor.

> If I disable vim-snippets, it works as expected. If no completion is found for the word it just inserts literal Tabs.

That's not how supertab works, so something else must be mapped to your tab or there is more to this.

**Comment by NerdPad** [comment]
Okay, thanks for pointing that out.
