### ISSUE TITLE
<tab> is not completing

### ISSUE THREAD

**Issue by petervaro** [ervandew/supertab#180]
When I use `<C-n>` or `<C-p>` the completion window pops up, however it is not working with `<tab>`. I did `:verbose imap <tab>` and it says:

```
i  <Tab>         <Plug>SuperTabForward
        Last set from /usr/share/vim/vimfiles/plugin/supertab.vim
```

Which means it should work, yet it does not. My setup is: `urxvt` + `tmux` + `vim`, the latest from everything.

**Comment by petervaro** [comment]
All right, I found the problem: if `.vimrc` has `:set paste` then it will prevent the popup to work.. I guess setting a global `paste` is not a good idea after all :/ I'm closing this issue now, though interested in any workarounds!

**Comment by petervaro** [comment]
I recently saw, that this problem came up before: #24, now I'm not saying that vim/plugin should give me warning messages, but this problem should be mentioned in the documentation/FAQ.

**Comment by erikrtn** [comment]
This should definitely be in the docs / FAQ.

Has anyone come up with a better workaround than `:set nopaste`? I usually like paste on in my `.vimrc`; just happen to need tab completion more.
