### ISSUE TITLE
Going backward with <tab> and forward with <s-tab>

### ISSUE THREAD

**Issue by tgy** [ervandew/supertab#182]
I installed supertab with default configuration and am using it with neovim 0.1.7.

When I press `<tab>` the completion is going backward in the completion list and when I press `<s-tab>` it's going forward. I don't know what's happening, it's very strange.

I have tried the following but it didn't change anything.

```vim
let g:SuperTabMappingForward = '<tab>'
let g:SuperTabMappingBackward = '<s-tab>'
```

I also tried to reverse those two settings. No luck.

**Comment by ervandew** [comment]
See the second question under "Frequently Asked Questions": https://github.com/ervandew/supertab

**Comment by tgy** [comment]
Ah damn, sorry. I should have read that!
