### ISSUE TITLE
Show auto completion options while typing

### ISSUE THREAD

**Issue by vonum** [ervandew/supertab#196]
Hi, not sure if this is an issue or me missing something in the docs.

Is there a way to set up the plugin to show the auto completion list while typing?
That would mean not having to press <TAB> for the auto completion options to become visible.

Love the plugin,
Thanks

**Comment by ervandew** [comment]
There are other plugins that provide that functionality. Valloric/YouCompleteMe may still be the most popular one, but I'm not totally sure.
