### ISSUE TITLE
vim writes 4 spaces instead of a tab when supertab is installed

### ISSUE THREAD

**Issue by orendanniel015** [ervandew/supertab#201]
I write a lot of python code where, it is not that nice to mix tabs with spaces since my code is written with tabs it is problematic for me to use 4 spaces. any how from some weird reason when I have supertab and I type tab(when there is no character behind the cursor) it writes 4 spaces. How can I force vim to use tabs when supertab is installed.

Thanks for the help!

**Comment by ervandew** [comment]
When not completing, supertab will send a `<tab>` character, so in that case it should be no different with or without supertab installed. 

What is the result of running the following in vim:
* `:verbose set expandtab?`

**Comment by orendanniel015** [comment]
Hello ervandew and thanks for your quick response!
It returns expandtab

**Comment by orendanniel015** [comment]
I have found the problem from some strange reason Vundle changes the tab behavior of vim.
After I have changed to pathogen the tab behavior works as expected.

**Comment by ervandew** [comment]
weird. i wonder if vundle was loading a file that pathogen isn't. That verbose command I gave you should show the name of the last file that modified the setting. If it didn't, then perhaps something else was going on. Either way, glad you were able to work around the problem.
