### ISSUE TITLE
Disable for a filetype

### ISSUE THREAD

**Issue by Boncom99** [ervandew/supertab#212]
I am trying to disable supertab just for .tex files and I don't see a way to do it. 

thanks for the help

**Comment by kflak** [comment]
+1 on this. Would love to see this implemented!

**Comment by vphantom** [comment]
This works for me (based on #132):

```text
" Stand down for Makefiles
au Filetype make let b:SuperTabDisabled = 1
```

**Comment by kflak** [comment]
Thanks!
