### ISSUE TITLE
On-the-fly completion

### ISSUE THREAD

**Issue by Tagussan** [ervandew/supertab#214]
Hi,

Is it possible to start completion immediately after I enter insert mode? To start completion, I need to press Tab.
It would be a great speed-up if the completion starts after I enter insert mode and type a few characters.

Maybe I can add this in my vimrc: `autocmd InsertCharPre * call <<function>>` to achieve this, but I could not figure out which function to set.

Thanks

**Comment by ervandew** [comment]
there are other completion plugins designed to auto open the completion menu as you type, so I don't think this is something that should be added to supertab.
