### ISSUE TITLE
vim supertab is loaded but does not map <tab>

### ISSUE THREAD

**Issue by pelegm** [ervandew/supertab#223]
* I installed `supertab` via `Vundle`.
* I am using Ubuntu 22.04, and my `~/.vim/bundle/supertab` folder is the most recent commit of the corresponding github repo.
* In my `.vimrc` I have the line `Plugin 'ervandew/supertab'`.
* When running `:scriptnames`, I see the line:
  ```
  40: ~/.vim/bundle/supertab/plugin/supertab.vim
  ```

However, `<tab>` doesn't seem to do anything. And, indeed, running `:verbose imap <tab>` returns `No mapping found`.

What am I doing wrong?

**Comment by jfecroft** [comment]
I have the same issue. Supertab now require vim version 9 or greater https://github.com/ervandew/supertab/commit/8c638fe17b470f4a27554cdf8e641bafa5e2a7a4 . If you update vim it should now work.

**Comment by pelegm** [comment]
Thank you, this is really helpful.
