### ISSUE TITLE
Predefined "snippets"

### ISSUE THREAD

**Issue by daGrevis** [ervandew/supertab#58]
Are there any way to define predefined "snippets" what will show up when Tab is hit? Even more, they could be language specific.

Lets example that my Vim doesn't have any tabs or splits opened and I create new file.

`:e main.js`

I type `funct` and hit Tab.

What I see is `function` option.

Is it somehow possible or are there any plans to implement it?

Thanks!

**Comment by ervandew** [comment]
> is there any way to show the pre-defined snippets in the popup menu when you hit `<tab>` (rather than expanding the snippet directly, which is the current behavior of supertab)?

Supertab doesn't have any snippet feature or integration with any of the snippet plugins. The snippet plugins instead usually integrate with supertab by overriding supertab's `<tab>` mappings and attempting to complete a snippet first, then delegating to supertab if no snippet was found.

> If YCM can do, then I believe supertab can do also, right?

Supertab doesn't attempt to populate the completion menu at all or provide any completion features beyond what vim already has, it simply helps decide what keystrokes to send to vim to let it perform the completion for you.  YCM on the other hand looks to be providing their own completion engine and not using vim's, so they have full control over what completions to present to you.
